<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <title>Dead Poets Society</title>
  <link rel="stylesheet" href="/css/1.css">  
  <link rel="stylesheet" href="/css/base.css">
</head>

<body>
  <!-- Include Navbar -->
  <header>
    <#include "components/navbar.ftl">
  </header>
<main class="d-grid gap-5 mt-5 py-5 mx-auto" style="width: 900px;">

<h3 class="pb-4 mb-4 fst-italic border-bottom">
    Контактная информация
</h3>
<b1 class="lead text-body-secondary">Для получение информации о доставке товара на конкретную дату и время получателю, свяжитесь с нашини комсультантами</b1>
<p class="lead text-body-secondary"> Контактные номера:<br> +375336895456<br>
                      +375334567892<br>
                      +375447585645</p>

  <#include "components/footer.ftl">
  </main>
</body>

</html>